name: 功能建议
description: 提议新的功能或改进
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: 使用场景
    validations:
      required: true
  - type: textarea
    attributes:
      label: 建议方案
    validations:
      required: true
  - type: textarea
    attributes:
      label: 隐私、成本与准确性影响
